### ISSUE TITLE
Create context and template to make configuration smarter.

### ISSUE THREAD

**Issue by gianarb** [gianarb/orbiter#3]
We need to get env vars during the configuration parsing in order to have the ability to inject environment variables.

Just to make all flexible we can use golang template engine and an object that right now only support env vars. Something like:

```
autoscalers:
  infra_scale:
    provider: digitalocean
    parameters:
      token: {{ .Env.DIGITALOCEAN_TOKEN }}
      region: nyc3
      size: 512mb
      image: ubuntu-14-04-x64
      key_id: 163422
      # https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting
      userdata: |
        #cloud-config

        runcmd:
          - sudo apt-get update
          - wget -qO- https://get.docker.com/ | sh
    policies:
      frontend:
        up: 2
        down: 3
```
In this way we can add something more in the future if we need and not just env vars.
