### ISSUE TITLE
[COMMUNITY HELP!!] Site docs and so on

### ISSUE THREAD

**Issue by gianarb** [gianarb/orbiter#49]
Now that we have a logo, some documentation and the project is reaching a good stability I think we should think about a static fancy site. As you probably now I am not able to make anything good in terms of colors and design.

** I am looking for some help!! **

**Comment by bvis** [comment]
I'm used to use `mkdocs` and I think it's simple and powerful.

You just need to use markdown in your doc files, and create an index file to give them a title and define a navigation menu. I'm currently using this docker image for this purpose: [MKDocs Material](https://hub.docker.com/r/squidfunk/mkdocs-material/).

In summary:
- I've a stack file with the definition of the docs of the site and I'm using it for CD of the docs.
- `docker-compose.docs.yml`
```
version: "3.1"

networks:
  docs-network:

services:
  docs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    image: REGISTRY/IMAGE:${PROJECT_DOCS_VERSION:-local}
    networks:
      - docs-network
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
```
- For development I have an extended `docker-compose.docs.override.yml` file:
```
version: "3.1"

services:
  docs:
    volumes:
      - ./docs:/docs/docs
      - ./docs/mkdocs.yml:/docs/mkdocs.yml
    ports:
      - "8000:8000"
```

In my docs folder I have the `Dockerfile`, the `mkdocs.yml`and the Markdown files.

- `Dockerfile`
```
FROM squidfunk/mkdocs-material:1.7.4

COPY ./docs /docs/docs
COPY ./docs/mkdocs.yml /docs/mkdocs.yml
```

- `mkdocs.yml`
```
site_name: Doc Title
pages:
  - Home: index.md
  - Section1:
    - Page1: page1-1.md
    - Page2: page1-2.md
  - Section2:
    - Page1: page2-1.md
    - Page2: page2-2.md
    - Etc
repo_url: https://my-repo.address
edit_uri: src/master/docs/
site_author: It's me
copyright: Copyright © 2017 My Copyright
strict: true
theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - toc
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
```
- Another thing I do is to create a symbolic link in the project from the `docs/index.md` to the `README.md` file to not to duplicate the initial project description.

All you need from here is just to play with some configuration options and integrate the deployment with your favourite tool for CD.

If you like this idea I could provide you more details.
