### ISSUE TITLE
Service starts but not use the port that is specified

### ISSUE THREAD

**Issue by luizbob** [gianarb/orbiter#59]
```
version: "3.4"

services:
  orbiter:
    image: gianarb/orbiter
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1

```
Even if i put the ports diferently, or 8000, this happens

`"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "589789cd6bdacc517390d98ae5430560b6f1274b84f59b6ecd26ca06dc9d31a6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},`

And i cannot access the container, the only way that i find for me to use it is following this

https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container/26622041#26622041

Please, help!
